spring:
  application:
    name: springboot-dubbo-demo
dubbo:
  #扫描包路径
  scan:
    base-packages: springboot.dubbo.rpc.service.impl
  #应用id,name
  application:
    id: springboot-dubbo-demoService
    name: springboot-dubbo-demoService
  #服务提供者协议配置
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  #注册信息
  registry:
    id: demoService
    #zookeeper地址
    address: zookeeper://192.168.1.134:2181
#使用springboot已集成的日志管理,如需要log4j等可自行配置
logging:
  file: ./logs/zhangyq-shop-springboot-service.log
